stages:
- name: Build artifactory
  steps:
  - runScriptConfig:
      image: maven:3.6-jdk-8-alpine
      shellScript: mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: CSUC/myapp:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: https://registry.pre.csuc.cat
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
