stages:
- name: Build artifactory
  steps:
  - runScriptConfig:
      image: maven:3.6-jdk-8-alpine
      shellScript: mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myapp:${CICD_EXECUTION_SEQUENCE}
      registry: docker-registry.docker-registry.172.31.17.227.xip.io:443
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
