kind: Service
apiVersion: v1
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  rules:
  - host: demo.paas.csuc.cat
    http:
      paths:
      - backend:
          serviceName: myapp-service
          servicePort: 8080
        path: /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: demo-app
        image: demo-app:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
